### ISSUE TITLE
import error in version 4.1.1 

### ISSUE THREAD

**Issue by Roxyi** [mkorpela/overrides#65]
Hi, I encountered an import error after upgrading overrides to 4.1.1.

Here is what I got
```
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 17:50:39) 
[GCC Clang 10.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import overrides
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/PycharmProjects/lib/python3.6/site-packages/overrides/__init__.py", line 1, in <module>
    from overrides.enforce import EnforceOverrides
  File "/opt/miniconda3/envs/PycharmProjects/lib/python3.6/site-packages/overrides/enforce.py", line 169, in <module>
    class EnforceOverrides(metaclass=EnforceOverridesMeta):
  File "/opt/miniconda3/envs/PycharmProjects/lib/python3.6/site-packages/overrides/enforce.py", line 133, in __new__
    setattr(getattr(mcls, method), "__ignored__", True)
AttributeError: 'int' object has no attribute '__ignored__'
```

**Comment by mkorpela** [comment]
Thanks for the information!

**Comment by ashwin153** [comment]
I'm not able to reproduce this on my local (Python 3.8), but maybe the solution here is to explicitly mark `requires` and `handle_special_value` as `__ignored__` instead of trying to automatically detect all public methods in https://github.com/mkorpela/overrides/blob/master/overrides/enforce.py#L7.

**Comment by brentyi** [comment]
+1 looks like I'm also having this issue! https://github.com/brentyi/jaxlie/runs/2427439998

It looks like CI in this repo was explicitly disabled for Python 3.6 (866f1ff52251323a0d50b51a0c89f476916b6af9), but the releases are still marked as 3.6-compatible.

**Comment by mkorpela** [comment]
I disabled the test as we do have syntax in tests that is not valid in python 3.6 or 3.7.
Tests were on only for a day as it was same day I put GH Actions on.

**Comment by mkorpela** [comment]
Reproduced this on linux:

```
❯ python3.6
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import overrides
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mkorpela/.local/lib/python3.6/site-packages/overrides/__init__.py", line 1, in <module>
    from overrides.enforce import EnforceOverrides
  File "/home/mkorpela/.local/lib/python3.6/site-packages/overrides/enforce.py", line 169, in <module>
    class EnforceOverrides(metaclass=EnforceOverridesMeta):
  File "/home/mkorpela/.local/lib/python3.6/site-packages/overrides/enforce.py", line 133, in __new__
    setattr(getattr(mcls, method), "__ignored__", True)
AttributeError: 'int' object has no attribute '__ignored__
```

**Comment by mkorpela** [comment]
8b67f1bc640b9f24b97f693ee2e45d62490e79a6 is the first bad commit

**Comment by mkorpela** [comment]
@Roxyi https://github.com/mkorpela/overrides/releases/tag/4.1.2
This issue should be now fixed with a patch release.
